### ISSUE TITLE
Support for android

### ISSUE THREAD

**Issue by samkit** [jnr/jffi#17]
Is there any plan to support android? Things like StubLoader doesn't support "armv7" CPU.
Would be good to know about the strategy.

May be helpful to make StubLoader like a application provided class (<application_package>.$StubLoader) using reflection and if application doesn't provide then fall back to "internal.StubLoader".

Happy to hear on this.

**Comment by headius** [comment]
Do you have an easy way to play with this on Android? If so, you'd just need to duplicate the logic we have for arm for armv7 or other platforms.

Stubloader could be made pluggable, but that seems like a bigger change than just adding platforms as they come along (since anyone plugging in would need to come up with the same code anyway).

**Comment by headius** [comment]
Stale issue, no followup. We do have ARM support, but need someone who can test this on Android.

**Comment by testn** [comment]
any specific reason why it does not work on android? https://github.com/abstractj/kalium/issues/25

**Comment by headius** [comment]
@testn I have heard rumors that Android applications run in a mode where one dynamic library cannot see another dynamic library in the same process. This would be due to how they implement library loading; if they're isolating the libraries, any FFI-like binding would fail to work...until we can load libraries in an appropriate way.

However, I have not gotten confirmation about this and have not had an opportunity to try this on Android myself.

**Comment by pepyakin** [comment]
There are several issues with JNR on the Android.

1. JNR expects that property `sun.arch.data.model` is always present which is not true for Android. It is enough to just define this property to `0` to workaround.
2. jffi tries to load native libraries from a JAR and it fails issue similar to OP's. Not to mention it is terribly slow on Android to load files from a JAR, it also doesn't work, because for some strange reason android gradle plugin strips all *.so files from JARs while packaging application. So only `.jnilib`, `.a` and `.dll` gets included. I didn't manage to solve this issue, so I just copy `libffi-1.2.so` from the bundled assets to the some folder in local file storage before accessing JNR.
3. As far as I can tell there is no libc on Android. Android uses it's own version of c library: [bionic](https://en.wikipedia.org/wiki/Bionic_(software)). So I guess #44 issue is because of this, but I'm not sure. Anyway, building `jffi` with android NDK toolchain helps, however some modifications to build are required.
4. [defineClass](https://github.com/jnr/jnr-ffi/blob/469727224e3a73f2db398df1113921f0e9d6313c/src/main/java/jnr/ffi/provider/jffi/NativeClosureProxy.java#L214) doesn't work because Android actually doesn't support loading Java bytecode.

**Comment by mirabilos** [comment]
Why is this closed if there is no support for Android yet?

**Comment by headius** [comment]
I believe jffi *does* work but there's some configuration required. Can we get some issues filed for specific problems (with fixes, ideally) so we can move forward on this?

I know we have done changes recently to support Android users, so it *can* work, but getting it there is apparently a bit trickier than it seems.

**Comment by mirabilos** [comment]
Charles Oliver Nutter dixit:

>I believe jffi *does* work but there's some configuration required. Can
>we get some issues filed for specific problems (with fixes, ideally) so
>we can move forward on this?

Sorry, no, I’ve implemented this in JNI now.

I *may* revisit this later and reimplement this in JNA for
desktop/server Java but I don’t know this yet. It was trying,
basically reimplementing DatagramChannel and DatagramSocket,
so I had to go with something I knew would work.

bye,
//mirabilos
PS: https://github.com/tarent/ECN-Bits under android/ecn-lib/
    (in case someone got curious)
-- 
tarent solutions GmbH
Rochusstraße 2-4, D-53123 Bonn • http://www.tarent.de/
Tel: +49 228 54881-393 • Fax: +49 228 54881-235
HRB 5168 (AG Bonn) • USt-ID (VAT): DE122264941
Geschäftsführer: Dr. Stefan Barth, Kai Ebenrett, Boris Esser, Alexander Steeg
