### ISSUE TITLE
Getting an error /tmp/jffi6958730225063734044.so: failed to map segment from shared object

### ISSUE THREAD

**Issue by vdua** [jnr/jffi#46]
I am using docker-maven-plugin which internally uses jnr/jffi (version 1.12.1) to open ubuntu socket and the plugin is failing with the error `Getting an error /tmp/jffi6958730225063734044.so: failed to map segment from shared object`
You can find attached the stack trace below (attaching it since it is around 380 lines)

Debugged it a little and found out that the issue is with the [loadFromJar](https://github.com/jnr/jffi/blob/master/src/main/java/com/kenai/jffi/internal/StubLoader.java#L354) API in StubLoader.java

Copying the lib file from jar to /tmp location using nio somehow corrupts the library and  triggering the error when loading the copied library using System.load. I verified that by writing a simple Java Program

```
import java.io.*;
import java.nio.channels.*;
public class Main {
   public static void main(String a[]) throws Exception {
        InputStream is = new FileInputStream(a[0]);
        FileOutputStream os = null;
        File dstFile = File.createTempFile("jffi", "." + dlExtension());
        dstFile.deleteOnExit();
        os = new FileOutputStream(dstFile);
        ReadableByteChannel srcChannel = Channels.newChannel(is);

        for (long pos = 0; is.available() > 0; ) {
            pos += os.getChannel().transferFrom(srcChannel, pos, Math.max(4096, is.available()));
         }

         os.close();
         os = null;
         System.load(dstFile.getAbsolutePath());
 }
}
```

When using this code with the library built for x86_64-Linux it gives me the same error. i.e. after running the following commands
```
javac Main.java
mvn clean install -Plinux-profile
java Main target/jni/x86_64-Linux/libjffi-1.2.so 
```

triggers the same error.

while if I change the code to directly load the library  (without any copying) it doesn't trigger an error.

System Details
OS: Ubuntu 16.04 
Arch: x86_64.
java version: 1.8.0_121 openjdk

The problem is that I am unable to reproduce that on a physical system with the same configuration. I am consistently able to reproduce that on the VMs that I have.

[stack.txt](https://github.com/jnr/jffi/files/835933/stack.txt)

**Comment by headius** [comment]
Wow, that's unusual. Have you checked what's different about the copied library versus the one in the jar?

I would be very surprised if they are actually different, but it should be easy to check.

I suspect this may be more about filesystem permissions. Some systems, for example SELinux setups, will not allow executable code to be loaded from /tmp, which is where we copy it. You could try forcing a different tmp dir using the appropriate environment variables.

If this turns out to be the case, I'm not sure about a solution. We need to put the jar *somewhere* and just throwing it in the current directory or something similar is sure to upset people. We put it in tmp so that if something happens to prevent us from deleting it at JVM exit, we're not cluttering up someone's home directory etc.

**Comment by vdua** [comment]
@headius Thanks. Your assumption is correct, somehow the system is not allowing library to be loaded from /tmp. By simply copying a library to /tmp using `cp` and loading using `System.load` is also throwing the same error.

Closing the bug as it is a permission issue.

**Comment by muka** [comment]
@vdua we are running the same issue in a armhf docker container. What was the solution in your case?
