### ISSUE TITLE
Close library

### ISSUE THREAD

**Issue by david-bouyssie** [jnr/jffi#98]
Is there a way to close a previously opened library? 
I would like to delete the dll file associated to a given loaded library when I don't need it anymore.

**Comment by headius** [comment]
There is no way to do this when the libraries are loaded by the JVM, unfortunately. This is an issue that all projects with a jar-packaged DLL have to deal with, such as in https://github.com/tensorflow/tensorflow/issues/18397.

This issue is more of a general JVM question, for which the answer is "no, or at least not easily" so I will close this and continue discussion on #97.

**Comment by david-bouyssie** [comment]
So I guess it's not possible to delete a loaded dll inside the running JVM?
